[build]
# Build the backend and frontend
build = "cd backend && npm install && npm run build && cd ../frontend && npm install && npm run build"

[start]
# Start both the backend and frontend
start = "cd backend && npm start & cd frontend && npx serve -s build -l 3000"
